apiVersion: v1
kind: BuildConfig
metadata:
  name: petclinic-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
          agent any 
          stages {
            stage("Clone Source") {
              steps {
                checkout([$class: 'GitSCM',
                            branches: [[name: '*/master']],
                            extensions: [
                              [$class: 'RelativeTargetDirectory', relativeTargetDir: 'petclinic']
                            ],
                            userRemoteConfigs: [[url: 'https://github.com/samospam/spamyproject']]
                        ])
              }
            }
            stage("Build JAR") {
              steps {
                dir('spamyproject') {
                  sh 'mvn clean install -DskipTests'
                }
              }
            }
            stage("Build Image") {
              steps {
                dir('mavenapp/target') {
                  sh 'oc start-build petclinic --from-dir . --follow'
                }
              }
            }
          }
        }
    type: JenkinsPipeline
  triggers: []
