apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: petclinictaketwo
  name: petclinictaketwo
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8080
  selector:
    io.kompose.service: petclinictaketwo
status:
  loadBalancer: {}
