kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "petclinic-build" 
spec:
  runPolicy: "Serial" 
  triggers: 
      type: "ImageChange"
  source:
    images:
       from:
        kind: "ImageStreamTag"
        name: "samospam/petclinic:latest"
  strategy:
    type: "Source" 
    sourceStrategy:
      from:
        kind: "ImageStreamTag"
        name: "samospam/petclinic:latest"
      forcePull: true 
