apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: petclinictaketwo
  name: petclinictaketwo
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8080
  selector:
    io.kompose.service: petclinictaketwo
status:
  loadBalancer: {}
